Chore/tgyuu/#13
pknu-wap/WAPP pull request #23
Opened 2023-10-05 17:03 UTC by tgyuuAn

## 1. 📄 관련된 이슈 및 소개
closed #13 

## 2. 🔥변경된 점

- BaseFragment 생성
- BottomNaivgationView + FragmentContainerView생성
- Feature 바텀네비게이션 뷰로 이동할 수 있는 각 모듈 생성 (모듈만 생성)
- 네비게이션과 각 모듈 연결

## 3. 📸 스크린샷(선택)

https://github.com/pknu-wap/WAPP/assets/116813010/4aa7f33a-281e-4ac2-b0ba-42c831a9a2a2

귀찮아서 Text안바꿨는데 다 다른화면 맞아요 ㅋㅋ

## 4. 💡알게된 혹은 궁금한 사항들

아래 영상처럼 **기본 primary 색상(분홍색)** 으로 뒤에 동그란 타원형 생기는데,

저거 이름 알아내느라고 삽질 오지게 했네요.

https://github.com/pknu-wap/WAPP/assets/116813010/8f81d814-af60-4e0f-8f58-809f0c64b5a1

<br><br><br><br>

일단 위에 영상처럼 분홍색 소시지 생기는거 이름은 **Activie Indicator** 였어요.
<br><br><br>

![image](https://github.com/pknu-wap/WAPP/assets/116813010/a26e8185-4769-4b4e-b364-8b25f2dab282)

출처 : https://stackoverflow.com/questions/70397792/how-to-change-the-color-of-active-indicator-bottombavigationview-material-you-m

<br><br><br>

이름 알게 되니까 stack overflow에 바로 나오더라고요..

<br><br>

**1. parent 가 "Widget.Material3.BottomNavigationView.ActiveIndicator" 인 새로운 style 정의**  
<br>
``` kotlin
    <style name="Style.BottomNavigationView.Custom.Indicator" parent="Widget.Material3.BottomNavigationView.ActiveIndicator">
        <item name="android:color">@android:color/transparent</item>
    </style>
```

<br><br>

**2.  아래 그림처럼 itemActiveIndicatorStyle 에 위에서 만들어준 컼스텀 스타일 적용하면 끝**
<br>
``` kotlin
        <com.google.android.material.bottomnavigation.BottomNavigationView
            android:id="@+id/bnv_main_bottomNaviView"
            android:layout_width="match_parent"
            android:layout_height="70dp"
            android:background="@color/gray_2"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:itemTextColor="@drawable/selector_text_color"
            app:layout_constraintStart_toStartOf="parent"
            app:labelVisibilityMode="labeled"
            app:itemActiveIndicatorStyle="@style/Style.BottomNavigationView.Custom.Indicator"
            app:menu="@menu/menu_main" />
```
<br>

출처 : https://stackoverflow.com/questions/70397792/how-to-change-the-color-of-active-indicator-bottombavigationview-material-you-m

허무하네요.

2023-10-05 17:04 UTC, tgyuuAn commented
File Change 많은 건 모듈이 여러 개 생성해서 그래요!

실제로 코드 까보시면 코멘트 달아주실 거 별로 없을거에욥

2023-10-06 01:41 UTC, jeongjaino requested changes
하하 다 셋업 관련된 코드라 별 다른 이상은 없어보이네요!! 

많은 모듈 생성하시고 빌드하시느라 고생많으셨습니다. .

생성하신 모듈에서 kotlin build 플러그인만 소거하시면 될 것 같아요!!

2023-10-06 01:41 UTC, jeongjaino commented on app/src/main/java/com/wap/wapp/MainActivity.kt
> +            bnvMainBottomNaviView.itemIconTintList = null
nvMainBottomNaviView.itemIconTintList = null 는 어떤 동작을 수행하나요??

바텀바 아이콘 색을 다 빼는 코드인가요?

2023-10-06 01:41 UTC, jeongjaino commented on feature/manage/build.gradle.kts
alias(kotlin) 해당 부분 

제가 만든 Feature Covnention에 
                apply("org.jetbrains.kotlin.android")
                코틀린 빌드 플러그인도 들어있어서 중복되는 것 같아요!!

2023-10-06 01:41 UTC, jeongjaino commented on app/src/main/res/drawable/ic_manage.xml
드로어블 네이밍 컨벤션 아주 좋습니다!!!

2023-10-06 04:54 UTC, tgyuuAn commented on app/src/main/res/drawable/ic_manage.xml
첨에 막 하다가 뒤늦게 컨벤션 보고 수정했어요 하하..

2023-10-06 04:57 UTC, tgyuuAn commented on feature/manage/build.gradle.kts
수정하겠씁니다.

혹시 다음부터 코멘트 그 코드 부분 블럭 쳐주실 수 있나요?!

파일 들어가서 찾아야해서요 ㅠㅠ

2023-10-06 05:03 UTC, tgyuuAn commented on app/src/main/java/com/wap/wapp/MainActivity.kt
> +            bnvMainBottomNaviView.itemIconTintList = null
https://github.com/pknu-wap/WAPP/assets/116813010/1dd581be-594d-446e-be31-824bb733c427

저걸 안넣어주면 위 영상처럼 Selector drawalbe의 Icon 색상 넣어준 걸 적용 시키지 못해욥

출처 : https://velog.io/@sainkr/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-bottomnavigation-icon-%EA%B7%B8%EB%8C%80%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EB%B2%95

2023-10-06 05:03 UTC, tgyuuAn commented on feature/manage/build.gradle.kts
아 저게 자동으로 생성된건데 왜 그런 걸까요 ..?

2023-10-06 05:12 UTC, jeongjaino approved these changes
고생하셨습니다~!!

2023-10-06 05:13 UTC, jeongjaino commented on feature/manage/build.gradle.kts
오잉 정말요? 

나중에 풀받고 해볼게요,,!!

2023-10-06 05:14 UTC, jeongjaino commented
Tgyuu 의  장학금 축하드립니다  > _ <  (회식 기대할게요)

2023-10-06 05:15 UTC, tgyuuAn commented
예????????????????????

2023-10-06 05:15 UTC, merged